In [5]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('../src')
import torch
import numpy as np
from rl.tasking_env import TaskingEnv

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
env = TaskingEnv(x0=[0, 0, 0, 0.5, 0.5, 0.5, 0.5])

for i in range(500):
    env.step(torch.tensor([0.01, 0, 0, 0]))
    env.render()

env.close()

[0.001 0.    0.    0.5   0.5   0.5   0.5  ]
[0.002    0.       0.       0.499975 0.500025 0.500025 0.499975]
[0.003    0.       0.       0.499925 0.500075 0.500075 0.499925]
[0.004      0.         0.         0.49984999 0.50014999 0.50014999
 0.49984999]
[0.005      0.         0.         0.49974996 0.50024996 0.50024996
 0.49974996]
[0.006      0.         0.         0.49962489 0.50037489 0.50037489
 0.49962489]
[0.007      0.         0.         0.49947478 0.50052478 0.50052478
 0.49947478]
[0.008     0.        0.        0.4992996 0.5006996 0.5006996 0.4992996]
[0.009      0.         0.         0.49909932 0.50089932 0.50089932
 0.49909932]
[0.01       0.         0.         0.49887391 0.50112391 0.50112391
 0.49887391]
[0.011      0.         0.         0.49862335 0.50137335 0.50137335
 0.49862335]
[0.012      0.         0.         0.4983476  0.50164759 0.50164759
 0.4983476 ]
[0.013      0.         0.         0.49804661 0.5019466  0.5019466
 0.49804661]
[0.014      0.         0.         0